#!/usr/bin/env bash
# Link stubs for Sony system libraries, installed next to the SDK's own stubs
# in $PS5_PAYLOAD_SDK/target/lib:
#   libSceVideodec2  hardware video decoder (xbmc/platform/ps5/video); the
#                    SDK ships no stub for it
#   libSceVideoOut   the SDK's stub plus sceVideoOutVrrUnpegFromFixedRate
#                    (VRR); generated from the SDK's own stub, which is kept
#                    as libSceVideoOut.so.sdk
#
# Both are plain symbol-name stubs resolved by the payload runtime linker at
# load time - they contain no Kodi-specific logic and exist only because the
# SDK does not ship them yet. See docs/ps5/upstream-migration-tasks.md: once
# upstream carries them, this script and shims/sce_stubs can be dropped.
#
# Run by tools/ps5/bootstrap.sh; safe to re-run.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
export PS5_PAYLOAD_SDK="${PS5_PAYLOAD_SDK:-/opt/ps5-payload-sdk}"
DEST="$PS5_PAYLOAD_SDK/target/lib"
CC="$PS5_PAYLOAD_SDK/bin/prospero-clang"

# plain ld.lld first: the SDK's prospero-lld wrapper always adds -pie, which
# cannot be combined with -shared
LLD=""
for candidate in "$(command -v ld.lld || true)" "$(command -v ld.lld-18 || true)" \
                 "$PS5_PAYLOAD_SDK/bin/ld.lld"; do
  [ -n "$candidate" ] && [ -x "$candidate" ] && { LLD="$candidate"; break; }
done
[ -x "$CC" ] || { echo "!! $CC not found"; exit 1; }
[ -n "$LLD" ] || { echo "!! no ld.lld found (install: sudo apt install lld)"; exit 1; }
echo "using $CC and $LLD"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

for stub in "$ROOT"/shims/sce_stubs/*.c; do
  name="$(basename "$stub" .c)"
  "$CC" -ffreestanding -fno-builtin -nostdlib -fPIC \
    -c -o "$TMP/$name.o" "$stub"
  "$LLD" -m elf_x86_64 -shared -soname "$name.sprx" \
    -o "$TMP/$name.so" "$TMP/$name.o"
  sudo install -m644 "$TMP/$name.so" "$DEST/"
  echo "installed $name stub into $DEST"
done

# libSceVideoOut: the SDK stub's symbols plus the VRR unpeg function.
NM="$PS5_PAYLOAD_SDK/bin/llvm-nm"
[ -x "$NM" ] || NM="$(command -v llvm-nm-18 || command -v llvm-nm)"
READELF="$(command -v llvm-readelf-18 || command -v llvm-readelf || command -v readelf)"
ORIG="$DEST/libSceVideoOut.so.sdk"
[ -f "$ORIG" ] || sudo cp -p "$DEST/libSceVideoOut.so" "$ORIG"
SONAME="$("$READELF" -d "$ORIG" | sed -n 's/.*(SONAME).*\[\(.*\)\].*/\1/p')"
[ -n "$SONAME" ] || { echo "!! no SONAME in $ORIG"; exit 1; }
{
  echo "/* generated by tools/ps5/bootstrap/sce-stubs.sh from $(basename "$ORIG") */"
  "$NM" -D --defined-only "$ORIG" | while read -r _ type name; do
    case "$type" in
      T|t|W|w) echo "void $name(void) {}" ;;
      D|d|B|b|R|r|V|v) echo "int $name;" ;;
    esac
  done
  grep -q " sceVideoOutVrrUnpegFromFixedRate$" <("$NM" -D --defined-only "$ORIG") || \
    echo "void sceVideoOutVrrUnpegFromFixedRate(void) {}"
} > "$TMP/libSceVideoOut.c"
COUNT="$(grep -c '^void \|^int ' "$TMP/libSceVideoOut.c")"
"$CC" -ffreestanding -fno-builtin -nostdlib -fPIC -w -c -o "$TMP/libSceVideoOut.o" "$TMP/libSceVideoOut.c"
"$LLD" -m elf_x86_64 -shared -soname "$SONAME" -o "$TMP/libSceVideoOut.so" "$TMP/libSceVideoOut.o"
"$NM" -D --defined-only "$TMP/libSceVideoOut.so" | grep -q " sceVideoOutVrrUnpegFromFixedRate$" || {
  echo "!! generated libSceVideoOut stub lacks the unpeg function"; exit 1; }
sudo install -m644 "$TMP/libSceVideoOut.so" "$DEST/libSceVideoOut.so"
echo "installed libSceVideoOut stub ($COUNT symbols incl. sceVideoOutVrrUnpegFromFixedRate, soname $SONAME) into $DEST"
